"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const middlewares_1 = require("../middlewares");
const gameEvaluationQuestion_1 = require("../controllers/gameEvaluationQuestion");
const router = (0, express_1.Router)();
router.use(middlewares_1.middleware.useAuthorization);
router.get('/', gameEvaluationQuestion_1.gameEvaluationQuestionController.findAll);
router.get('/detail/:id', gameEvaluationQuestion_1.gameEvaluationQuestionController.findByDetail);
router.post('/', gameEvaluationQuestion_1.gameEvaluationQuestionController.create);
router.patch('/', gameEvaluationQuestion_1.gameEvaluationQuestionController.update);
router.delete('/:id', gameEvaluationQuestion_1.gameEvaluationQuestionController.remove);
exports.default = router;
